# Generated by Django 3.2.9 on 2022-03-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('against', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
            ],
            options={
                'db_table': 'standings',
            },
        ),
    ]
